/**
 * Format rows into CSV / JSON / SQL strings. Identifier safety handled by caller;
 * value escaping handled here per format.
 */
import { quoteIdent, type DriverType } from "./dbConnector";

export type ExportFormat = "csv" | "json" | "sql";

function csvCell(v: unknown): string {
  if (v === null || v === undefined) return "";
  let s: string;
  if (typeof v === "bigint") s = v.toString();
  else if (v instanceof Date) s = v.toISOString();
  else if (typeof v === "object") s = JSON.stringify(v);
  else s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function toCsv(columns: string[], rows: Record<string, unknown>[]): string {
  const lines = [columns.map(csvCell).join(",")];
  for (const r of rows) {
    lines.push(columns.map((c) => csvCell(r[c])).join(","));
  }
  return lines.join("\r\n") + "\r\n";
}

function jsonReplacer(_key: string, value: unknown): unknown {
  if (typeof value === "bigint") return value.toString();
  if (value instanceof Date) return value.toISOString();
  if (value instanceof Buffer || value instanceof Uint8Array) return `0x${Buffer.from(value).toString("hex")}`;
  return value;
}

export function toJson(rows: Record<string, unknown>[]): string {
  return JSON.stringify(rows, jsonReplacer, 2);
}

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "bigint") return v.toString();
  if (v instanceof Date) return `'${v.toISOString()}'`;
  if (v instanceof Buffer || v instanceof Uint8Array) return `X'${Buffer.from(v).toString("hex")}'`;
  const s = typeof v === "object" ? JSON.stringify(v) : String(v);
  return `'${s.replace(/'/g, "''")}'`;
}

export function toSqlInserts(
  driver: DriverType,
  database: string,
  table: string,
  columns: string[],
  rows: Record<string, unknown>[]
): string {
  const fq = `${quoteIdent(database, driver)}.${quoteIdent(table, driver)}`;
  const colList = columns.map((c) => quoteIdent(c, driver)).join(", ");
  const stmts: string[] = [
    `-- Export from ${database}.${table} (${rows.length} rows)`,
    `-- Generated by DatabaseManager`
  ];
  for (const r of rows) {
    const vals = columns.map((c) => sqlLiteral(r[c])).join(", ");
    stmts.push(`INSERT INTO ${fq} (${colList}) VALUES (${vals});`);
  }
  return stmts.join("\n") + "\n";
}

export function contentType(format: ExportFormat): string {
  if (format === "csv") return "text/csv; charset=utf-8";
  if (format === "json") return "application/json; charset=utf-8";
  return "application/sql; charset=utf-8";
}

export function fileExtension(format: ExportFormat): string {
  return format;
}
